baseURL = "http://gobbe.net/"
languageCode = "en-gb"
title = "gobbe.NET"
theme = "ananke"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4