baseURL = "https://gobbe.net/"
languageCode = "en-gb"
title = "gobbe.NET"
theme = "hugo-coder"
defaultcontentlanguage = "en"
enableRobotsTXT = true

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "ggobbe"
    info = "Software Developer"
    description = "gobbe.NET blog"
    keywords = "blog,developer,personal,code,software"
    avatarurl = "images/avatar.png"

    hidecredits = true
    hidecopyright = true

    math = false

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/ggobbe/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "vs"
    tabWidth = 4